/* generated by pull.js */
import _js from "./theme3.js";
import _css from "!css-loader!./theme3.css";
import _css2 from "!css-loader!./black_text.css";
import _css3 from "!css-loader!./color_on_white.css";
import _css4 from "!css-loader!./color_on_black.css";
export const resources = {
  "theme3.js": _js,
  "theme3.css": _css,
  "black_text.css": _css2,
  "color_on_white.css": _css3,
  "color_on_black.css": _css4,
};
