name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup Node 16
          uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Install Dependencies
          run: npm ci --force
        - name: Build
          run: npm run build
        - name: Upload Build Artifact
          uses: actions/upload-artifact@main
          with:
            name: build
            path: build
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@main
        with:
          name: build
          path: build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
